### ISSUE TITLE
Support `sshkey` dependency

### ISSUE THREAD

**Issue by nickthecook** [nickthecook/ops#17]
```yaml
dependencies:
  sshkey:
    - keys/user@server
```

`ops` should generate the above key with no passphrase if it does not already exist.

`ops` could also print a stern warning to add the files or the directory to `.gitignore`. `ops` could actually add the file, if it finds a `.gitignore` file already there, and it looks like `git` isn't already ignoring the keys.
