### ISSUE TITLE
Add support for multiple aliases per action

### ISSUE THREAD

**Issue by ErikHumphrey** [nickthecook/ops#18]
Right now, an `ops` action can have one alias. Often, you only ever need one alias to make running an action faster: you would have a command and a short-form alias, e.g. `ops log`, with `ops l` aliased to it. However, sometimes you also might want to have more, especially if a developer's intuition is to run a synonym of a command or a slight variation on the word. An example of this would be wanting to run `ops log` instead of `ops logs` where the only alias available is already `ops l`. In the interest of allowing `ops` to work the first time every time for a developer that hasn't written or read the config, it would be nice to be able to configure actions to have multiple aliases, and allowing more aliases to be added for an action as necessary to increase productivity / accelerate workflow.

The existing functionality for a single `alias` should still work:

```yaml
actions:
  logs:
    command: tail -f /var/log/messages
    alias: l
```

But it would also be possible to use `aliases` as a collection:

```yaml
actions:
  logs:
    command: tail -f /var/log/messages
    aliases:
      - l
      - log
      - history
```

Maybe `alias` and `aliases` could be used in the same way as each other, i.e., the two would be interchangeable and using `aliases` / `alias` would not force you to use or not use a collections of aliases. This way, if you go from two aliases down to just one, or one alias to two aliases, you won't have to change the keyword.
