### ISSUE TITLE
Env-specific commands

### ISSUE THREAD

**Issue by nickthecook** [nickthecook/ops#2]
Sometimes an action should be performed differently in different environments.

E.g. if you're developing on MacOS, but production runs linux, different commands are required to start or stop services.

Support this syntax:

```
actions:
  start:
    development:
      command: brew service start myapp
   command: sudo service start myapp
```

`actions.start.command` will be the default in all environments unless overridden by the presence of an `action.start.#{environment}.command`.
