### ISSUE TITLE
`service` dependency

### ISSUE THREAD

**Issue by nickthecook** [nickthecook/ops#20]
Sometimes an app needs to have certain services running in order to function. These can be started as part of `ops up` using `custom` dependencies, but that is onerous when the app may be run on Mac or Linux. E.g.:

```yaml
dependencies:
  custom:
    - which brew && brew service start some_service || service start some_service
```

If `ops` had a `service` dependency, which was platform-aware, the dependency would look like this:

```yaml
dependencies:
  service:
    - some_service
```

which is nicer. Also, `ops down` would stop the services. Right now there's no way to write a custom command to be run on `ops down`.
