### ISSUE TITLE
Add support for multiple commands per action

### ISSUE THREAD

**Issue by ErikHumphrey** [nickthecook/ops#44]
Like #18, but allowing multiple commands to be specified as a typical YAML collection, to be executed in order / from the top down.

#### Considerations

Should having multiple commands in one action behave like `command1; command2; command3` or `command1 && command2 && command3`? Based on similar YAML command runners, probably the latter. The former could still be possible with something like `ignore_errors: true` on the action.

**Comment by nickthecook** [comment]
Good idea.

**Comment by nickthecook** [comment]
Turns out YAML defines convenient multi-line operators like `|` and `>-`. The pipe leaves newlines in the resulting string value:

```yaml
actions:
  deploy-container-image:
    command: |
      docker build -t $REGISTRY_URL/$IMAGE_NAME . && \
      docker push $REGISTRY_URL/$IMAGE_NAME
```

`>-` is equivalent, and concatenates all lines into one, removing the newlines:

```yaml
actions:
  deploy-container-image:
    command: >-
      docker build -t $REGISTRY_URL/$IMAGE_NAME . &&
      docker push $REGISTRY_URL/$IMAGE_NAME
```

The advantage of these YAML operators is that the user can use existing shell command separators like `;`, `||`, and `&&`, without `ops` needing to try to define and implement some similar behaviour.
